// ================================================================
// WriteUp — src/lib/curriculumData.js
// Vietnam MOET English Curriculum Data — Grades 7–12
// Source: Global Success textbook series writing tasks
// Used to calibrate feedback to grade level and task type
// ================================================================

const CURRICULUM = [
  { "grade": 7, "unit": 1, "title": "Hobbies", "topic": "Personal hobbies and leisure activities", "writingTask": "Write a paragraph of about 70 words about your hobby", "taskType": "descriptive", "targetWordCount": { "min": 60, "max": 80 }, "keyVocabulary": ["hobby", "collect", "enjoy", "spend time", "benefit", "patient"], "targetGrammar": ["present simple", "verbs of liking/disliking", "frequency adverbs"], "writingStructure": { "topicSentence": "State what your hobby is", "body": "When you started, who you share it with, what you need, benefits", "conclusion": "Why you enjoy it" }, "sampleErrors": ["Missing topic sentence", "No linking words between sentences", "Verb form error after frequency adverb"] },
  { "grade": 7, "unit": 2, "title": "Healthy Living", "topic": "Healthy habits and avoiding illness", "writingTask": "Write a passage of about 70 words to give advice on how to avoid viruses", "taskType": "descriptive", "targetWordCount": { "min": 60, "max": 80 }, "keyVocabulary": ["wear a mask", "exercise", "avoid crowds", "wash hands", "keep surroundings clean", "virus"], "targetGrammar": ["simple sentences", "imperative for advice", "should/shouldn't"], "writingStructure": { "topicSentence": "Introduce the health topic", "body": "Give 3–4 tips with brief reasons", "conclusion": "Encourage the reader" }, "sampleErrors": ["Imperative form incorrect", "No linking words between tips", "Tips listed without explanation"] },
  { "grade": 7, "unit": 3, "title": "Community Service", "topic": "Community activities and volunteer work", "writingTask": "Write an email about community activities one did last summer", "taskType": "descriptive", "targetWordCount": { "min": 70, "max": 90 }, "keyVocabulary": ["community", "volunteer", "activity", "benefit", "organise", "participate"], "targetGrammar": ["past simple", "time expressions", "linking words: and, but, because"], "writingStructure": { "topicSentence": "Introduce the activity and when it happened", "body": "Describe what you did and who you helped", "conclusion": "How it made you feel or what you learned" }, "sampleErrors": ["Present tense used instead of past tense", "Email opening/closing missing", "Events listed without explanation"] },
  { "grade": 7, "unit": 4, "title": "Music and Arts", "topic": "Music and art forms", "writingTask": "Write an informal letter of invitation to a music or arts event", "taskType": "noticeWriting", "targetWordCount": { "min": 70, "max": 90 }, "keyVocabulary": ["performance", "traditional", "musical", "instrument", "invite", "attend"], "targetGrammar": ["comparisons: like, different from, as...as", "informal register", "present and future tenses"], "writingStructure": { "topicSentence": "Greeting and reason for writing", "body": "Details of the event: what, when, where", "conclusion": "Invitation and sign-off" }, "sampleErrors": ["Formal register used in informal letter", "Missing event details", "No closing line"] },
  { "grade": 7, "unit": 5, "title": "Food and Drink", "topic": "Traditional foods and eating habits", "writingTask": "Write a paragraph describing eating habits", "taskType": "descriptive", "targetWordCount": { "min": 70, "max": 90 }, "keyVocabulary": ["traditional", "typical", "meal", "ingredient", "nutritious", "popular"], "targetGrammar": ["some, a lot of, lots of", "present simple for habits", "adverbs of frequency"], "writingStructure": { "topicSentence": "Introduce the food or eating habit", "body": "Describe what, when, and how it is eaten", "conclusion": "Why you like it or why it is popular" }, "sampleErrors": ["No topic sentence — jumps straight to listing foods", "Vague vocabulary (good, nice, delicious) without elaboration", "Mixing unrelated foods in one paragraph"] },
  { "grade": 7, "unit": 6, "title": "A Visit to a School", "topic": "Schools and school activities", "writingTask": "Write a paragraph about an outdoor activity at one's school", "taskType": "descriptive", "targetWordCount": { "min": 70, "max": 90 }, "keyVocabulary": ["facility", "activity", "outdoor", "event", "participate", "school club"], "targetGrammar": ["prepositions of time and place", "past simple", "present simple for descriptions"], "writingStructure": { "topicSentence": "Introduce the school and activity", "body": "Describe the activity, who participates, when it happens", "conclusion": "Why it is popular or enjoyable" }, "sampleErrors": ["Tense inconsistency between sentences", "Prepositions of time/place incorrect", "No concluding sentence"] },
  { "grade": 7, "unit": 7, "title": "Traffic", "topic": "Traffic rules and road safety", "writingTask": "Write a paragraph about traffic problems", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 70, "max": 90 }, "keyVocabulary": ["traffic jam", "road sign", "obey", "pedestrian", "vehicle", "helmet"], "targetGrammar": ["It indicating distance", "should/shouldn't", "because/so"], "writingStructure": { "topicSentence": "State the traffic problem", "body": "Describe causes and effects or solutions", "conclusion": "What people should do" }, "sampleErrors": ["Problem stated without cause or solution", "Should used without base verb", "Run-on sentences with no punctuation"] },
  { "grade": 7, "unit": 8, "title": "Films", "topic": "Types of films and film reviews", "writingTask": "Write a paragraph about a film", "taskType": "descriptive", "targetWordCount": { "min": 70, "max": 90 }, "keyVocabulary": ["action", "comedy", "animation", "character", "plot", "recommend"], "targetGrammar": ["connectors: although, though, however", "adjectives describing films", "past simple for plot summary"], "writingStructure": { "topicSentence": "Name and type of film", "body": "Brief plot, main character, why it is good or interesting", "conclusion": "Recommendation" }, "sampleErrors": ["Plot summary too long — no opinion given", "Connector used incorrectly", "No recommendation at the end"] },
  { "grade": 7, "unit": 9, "title": "Festivals Around the World", "topic": "Festivals and cultural celebrations", "writingTask": "Write an email to describe a festival", "taskType": "descriptive", "targetWordCount": { "min": 70, "max": 90 }, "keyVocabulary": ["festival", "celebrate", "traditional", "costume", "parade", "lantern"], "targetGrammar": ["Yes/No questions", "present simple for general facts", "past simple for personal experience"], "writingStructure": { "topicSentence": "Introduce the festival and where/when it happens", "body": "Describe activities, food, costumes", "conclusion": "How you felt or why it is special" }, "sampleErrors": ["Email format missing", "General facts only — no personal experience", "No concluding thought"] },
  { "grade": 7, "unit": 10, "title": "Energy Sources", "topic": "Types of energy and saving energy", "writingTask": "Write a paragraph about how to save energy at home", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 70, "max": 90 }, "keyVocabulary": ["solar", "renewable", "electricity", "save", "reduce", "energy source"], "targetGrammar": ["present continuous", "should for advice", "because/so"], "writingStructure": { "topicSentence": "Introduce the importance of saving energy", "body": "Give 3 practical tips at home", "conclusion": "Result if everyone follows these tips" }, "sampleErrors": ["Tips listed without reasons", "Present continuous misused for habitual actions", "No concluding impact statement"] },
  { "grade": 7, "unit": 11, "title": "Travelling in the Future", "topic": "Future means of transport", "writingTask": "Write a paragraph about the advantages of a future means of transport", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 70, "max": 90 }, "keyVocabulary": ["hyperloop", "flying car", "advantage", "convenient", "fuel", "passenger"], "targetGrammar": ["future simple: will/won't", "possessive pronouns", "comparative adjectives"], "writingStructure": { "topicSentence": "Name the means of transport and main claim", "body": "Give 2–3 advantages with reasons", "conclusion": "Why it will be popular in the future" }, "sampleErrors": ["Will + base verb form incorrect", "Advantages listed without explanation", "No future-oriented conclusion"] },
  { "grade": 7, "unit": 12, "title": "English-Speaking Countries", "topic": "Countries where English is spoken", "writingTask": "Write a diary entry about a tour of a city", "taskType": "descriptive", "targetWordCount": { "min": 70, "max": 90 }, "keyVocabulary": ["landmark", "capital", "population", "culture", "attraction", "tour"], "targetGrammar": ["articles: a/an/the", "past simple for diary", "rising and falling intonation (inferred)"], "writingStructure": { "topicSentence": "Where you went and when", "body": "What you saw and did", "conclusion": "How you felt about the experience" }, "sampleErrors": ["Diary format not used (no date, informal tone missing)", "Missing article errors", "No personal reaction at the end"] },
  { "grade": 8, "unit": 1, "title": "Leisure Time", "topic": "Leisure activities with family", "writingTask": "Write an email about leisure activities with friends", "taskType": "descriptive", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["leisure", "pastime", "gerund", "enjoy", "free time", "together"], "targetGrammar": ["verbs of liking/disliking + gerunds", "verbs of liking/disliking + to-infinitives", "present simple"], "writingStructure": { "topicSentence": "Introduce the leisure activity and who you do it with", "body": "Describe what you do and why you enjoy it", "conclusion": "Suggest or invite friend to join" }, "sampleErrors": ["Gerund vs infinitive error after like/enjoy", "Email format not used", "No invitation or closing"] },
  { "grade": 8, "unit": 2, "title": "Life in the Countryside", "topic": "Life and opinions about countryside vs city", "writingTask": "Write a paragraph about what someone likes or dislikes about life in the countryside", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["peaceful", "scenery", "fresh air", "inconvenient", "transportation", "community"], "targetGrammar": ["comparative forms of adverbs", "because/however", "present simple"], "writingStructure": { "topicSentence": "State overall opinion of countryside life", "body": "Give 2 things liked and 1 disliked (or vice versa) with reasons", "conclusion": "Overall preference statement" }, "sampleErrors": ["Adverb comparative form incorrect (more + adverb confusion)", "No contrast expressed", "Opinion not stated clearly"] },
  { "grade": 8, "unit": 3, "title": "Teenagers", "topic": "Teen stress and school clubs", "writingTask": "Write a paragraph about the cause(s) of one's stress and solutions to deal with it", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["pressure", "deadline", "overwhelmed", "cope with", "solution", "stress"], "targetGrammar": ["simple and compound sentences", "because/so/therefore", "should for advice"], "writingStructure": { "topicSentence": "Name the main cause of stress", "body": "Explain the cause and give 2 solutions", "conclusion": "Which solution is most effective and why" }, "sampleErrors": ["Cause described without solution", "Compound sentence joined only by comma (comma splice)", "Should + verb form error"] },
  { "grade": 8, "unit": 4, "title": "Ethnic Groups of Viet Nam", "topic": "Lifestyle of ethnic minority groups", "writingTask": "Write a paragraph about the things you do to help your family", "taskType": "descriptive", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["ethnic group", "minority", "custom", "household", "contribute", "chore"], "targetGrammar": ["Yes/No and Wh-questions", "countable and uncountable nouns", "present simple"], "writingStructure": { "topicSentence": "Introduce how you help your family", "body": "Describe 2–3 specific tasks you do", "conclusion": "Why helping your family is important" }, "sampleErrors": ["Countable/uncountable noun error", "Tasks listed without frequency or context", "No concluding statement about importance"] },
  { "grade": 8, "unit": 5, "title": "Our Customs and Traditions", "topic": "Customs and traditional festivals", "writingTask": "Write an email to give advice on taking part in a traditional festival", "taskType": "descriptive", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["custom", "tradition", "festival", "ceremony", "respectful", "ancestor"], "targetGrammar": ["zero article", "should/shouldn't for advice", "present simple for general truths"], "writingStructure": { "topicSentence": "Introduce the festival and why you are writing", "body": "Give 3 pieces of advice about behaviour or dress", "conclusion": "Encourage the reader and close warmly" }, "sampleErrors": ["Article errors (using 'the' with general nouns)", "Advice given without reasons", "Informal advice tone missing in email"] },
  { "grade": 8, "unit": 6, "title": "Lifestyles", "topic": "Modern vs traditional lifestyles", "writingTask": "Write a paragraph about the advantages or disadvantages of online learning", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["flexible", "convenient", "distraction", "self-discipline", "internet access", "blended learning"], "targetGrammar": ["future simple", "first conditional", "because/however/on the other hand"], "writingStructure": { "topicSentence": "State the position on online learning", "body": "Give 2–3 advantages or disadvantages with reasons", "conclusion": "Overall recommendation or prediction" }, "sampleErrors": ["First conditional form error (if + will)", "Advantages listed without reasons", "No clear position stated in topic sentence"] },
  { "grade": 8, "unit": 7, "title": "Environmental Protection", "topic": "National parks and environmental protection", "writingTask": "Write a paragraph about environmental protection", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["deforestation", "endangered", "pollution", "conservation", "ecosystem", "protect"], "targetGrammar": ["should/must for obligation", "passive voice (introduced)", "because/so/therefore"], "writingStructure": { "topicSentence": "State the environmental problem or solution", "body": "Give 2–3 reasons or actions", "conclusion": "Call to action or future prediction" }, "sampleErrors": ["Passive voice construction incorrect", "Environmental problems named without solutions", "No conclusion or call to action"] },
  { "grade": 8, "unit": 8, "title": "Shopping", "topic": "Shopping habits and preferences", "writingTask": "Write a paragraph about a shopping place", "taskType": "descriptive", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["market", "mall", "vendor", "bargain", "product", "convenient"], "targetGrammar": ["comparative adjectives", "present simple", "because/so"], "writingStructure": { "topicSentence": "Introduce the shopping place", "body": "Describe location, what is sold, why people go there", "conclusion": "Personal recommendation" }, "sampleErrors": ["Comparative adjective form error", "Description too general — no specific details", "No personal opinion at the end"] },
  { "grade": 8, "unit": 9, "title": "Natural Disasters", "topic": "Types and effects of natural disasters", "writingTask": "Write a paragraph about a natural disaster", "taskType": "descriptive", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["flood", "earthquake", "typhoon", "damage", "evacuate", "disaster relief"], "targetGrammar": ["past simple", "past continuous", "time expressions: when, while, after"], "writingStructure": { "topicSentence": "Name the disaster and when/where it happened", "body": "Describe what happened and its effects", "conclusion": "What was done to help or lesson learned" }, "sampleErrors": ["Past continuous used instead of past simple for completed actions", "Cause/effect relationship unclear", "No response or recovery information"] },
  { "grade": 8, "unit": 10, "title": "Communication in the Future", "topic": "Future ways of communicating", "writingTask": "Write a paragraph about the advantages and disadvantages of a way of communicating in the future", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["hologram", "telepathy", "instant", "privacy", "bandwidth", "connect"], "targetGrammar": ["future simple: will/won't", "first conditional", "on the other hand/however"], "writingStructure": { "topicSentence": "Name the communication method and introduce the discussion", "body": "2 advantages and 1 disadvantage (or vice versa)", "conclusion": "Overall assessment" }, "sampleErrors": ["Future tense form error", "Only advantages OR disadvantages given — no balance", "No topic sentence — jumps straight into points"] },
  { "grade": 8, "unit": 11, "title": "Science and Technology", "topic": "New technologies and inventions", "writingTask": "Write a paragraph about the benefits of an invention", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["invention", "technology", "transform", "efficient", "breakthrough", "impact"], "targetGrammar": ["present perfect", "gerunds and to-infinitives", "because/as a result"], "writingStructure": { "topicSentence": "Name the invention and its main benefit", "body": "Give 2–3 specific benefits with examples", "conclusion": "Overall impact on life" }, "sampleErrors": ["Present perfect form error (have + past participle)", "Benefits stated without examples", "Conclusion simply repeats the topic sentence"] },
  { "grade": 8, "unit": 12, "title": "Life on Other Planets", "topic": "Possibility of life on other planets", "writingTask": "Write a paragraph about the conditions needed for life on a planet", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 80, "max": 100 }, "keyVocabulary": ["atmosphere", "gravity", "water", "oxygen", "temperature", "habitat"], "targetGrammar": ["conditionals type 1", "modals: might, could, must", "because/therefore"], "writingStructure": { "topicSentence": "State whether you think life exists on other planets", "body": "Give 2–3 conditions necessary for life and explain", "conclusion": "Conclusion about possibility of life" }, "sampleErrors": ["Conditional type 1 form error (if + present, will + base)", "Conditions listed without explanation", "No concluding statement of belief or possibility"] },
  { "grade": 9, "unit": 1, "title": "Local Community", "topic": "Community helpers and local products", "writingTask": "Write a paragraph about a community helper", "taskType": "descriptive", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["community helper", "craft", "handicraft", "speciality", "contribute", "volunteer"], "targetGrammar": ["question words before to-infinitives", "phrasal verbs (1)", "present simple"], "writingStructure": { "topicSentence": "Introduce the community helper and their role", "body": "Describe what they do and why it matters", "conclusion": "How they have helped the community" }, "sampleErrors": ["Role described without impact", "Phrasal verb used incorrectly", "No evidence of contribution"] },
  { "grade": 9, "unit": 2, "title": "City Life", "topic": "City problems and solutions", "writingTask": "Write a paragraph about what you like or dislike about city life", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["congestion", "pollution", "convenience", "opportunity", "infrastructure", "urban"], "targetGrammar": ["double comparatives", "phrasal verbs (2)", "because/although/however"], "writingStructure": { "topicSentence": "State overall opinion of city life", "body": "Give 2 things liked and 1 disliked with reasons", "conclusion": "Overall preference" }, "sampleErrors": ["Double comparative form error", "Contrast not expressed clearly", "No opinion stated in conclusion"] },
  { "grade": 9, "unit": 3, "title": "Healthy Living for Teens", "topic": "Balanced lifestyle for teenagers", "writingTask": "Write a paragraph about how to manage time effectively", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["balance", "schedule", "priority", "productive", "deadline", "self-discipline"], "targetGrammar": ["modal verbs in first conditional sentences", "should/must", "because/so/therefore"], "writingStructure": { "topicSentence": "Introduce the challenge of time management for teens", "body": "Give 3 practical strategies with reasons", "conclusion": "Result if strategies are followed" }, "sampleErrors": ["First conditional form error", "Strategies listed without explanation", "No predicted outcome in conclusion"] },
  { "grade": 9, "unit": 4, "title": "Remembering the Past", "topic": "Old school days and life in the past", "writingTask": "Write a paragraph about old school days", "taskType": "descriptive", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["nostalgic", "traditional", "memory", "classroom", "teacher", "lesson"], "targetGrammar": ["past continuous", "wish + past simple", "used to"], "writingStructure": { "topicSentence": "Introduce the time period being described", "body": "Describe 2–3 features of school life in the past", "conclusion": "Personal reflection or comparison to today" }, "sampleErrors": ["Past continuous vs past simple confusion", "Wish clause form error", "No personal reflection — just a list of facts"] },
  { "grade": 9, "unit": 5, "title": "Our Experiences", "topic": "Memorable school experiences", "writingTask": "Write a paragraph about the most pleasant or unpleasant experience at school", "taskType": "descriptive", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["memorable", "embarrassing", "achievement", "proud", "challenge", "overcome"], "targetGrammar": ["present perfect", "adjectives describing experiences", "because/as a result/therefore"], "writingStructure": { "topicSentence": "Name the experience and state whether it was pleasant or unpleasant", "body": "Describe what happened and how you felt", "conclusion": "What you learned from the experience" }, "sampleErrors": ["Present perfect form error", "Feelings described without cause", "No lesson or reflection at the end"] },
  { "grade": 9, "unit": 6, "title": "Vietnamese Lifestyle: Then and Now", "topic": "Changes in Vietnamese family lifestyle", "writingTask": "Write an email about changes in your family life", "taskType": "descriptive", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["lifestyle", "modern", "traditional", "generation", "adapt", "transform"], "targetGrammar": ["verbs + to-infinitive", "verbs + V-ing", "used to vs now"], "writingStructure": { "topicSentence": "Introduce one key change in family lifestyle", "body": "Contrast how things were and how they are now", "conclusion": "Your opinion about whether the change is positive" }, "sampleErrors": ["Verb + to-infinitive vs V-ing confusion", "Changes described without comparison to the past", "Email format not used"] },
  { "grade": 9, "unit": 7, "title": "Natural Wonders of the World", "topic": "Natural landscapes and wonders", "writingTask": "Write a paragraph about a natural wonder/landscape in an area", "taskType": "descriptive", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["wonder", "landscape", "breathtaking", "formation", "ecosystem", "attract"], "targetGrammar": ["reported speech (Yes/No questions)", "relative pronouns", "present simple for facts"], "writingStructure": { "topicSentence": "Name the wonder and where it is", "body": "Describe its features and what makes it special", "conclusion": "Why people should visit it" }, "sampleErrors": ["Relative pronoun missing or incorrect", "Description too vague — no specific features", "No recommendation at the end"] },
  { "grade": 9, "unit": 8, "title": "Tourism", "topic": "Types of tours and travel experiences", "writingTask": "Write a paragraph introducing a tour", "taskType": "descriptive", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["itinerary", "destination", "accommodation", "highlight", "attraction", "package"], "targetGrammar": ["stress in words ending in -ic and -ious", "relative pronouns", "future simple for plans"], "writingStructure": { "topicSentence": "Name the tour and its main appeal", "body": "Describe destinations, activities, and duration", "conclusion": "Why this tour is recommended" }, "sampleErrors": ["Future tense not used for planned activities", "Tour described without specific highlights", "No persuasive conclusion"] },
  { "grade": 9, "unit": 9, "title": "World Englishes", "topic": "Varieties of English and language learning", "writingTask": "Write a paragraph about ways to improve an area of English learning", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["vocabulary", "pronunciation", "fluency", "strategy", "immersion", "practice"], "targetGrammar": ["defining relative clauses", "stress in words ending in -ion and -ity", "suggest/advise/recommend + V-ing"], "writingStructure": { "topicSentence": "Name the area of English to improve", "body": "Give 3 strategies with brief explanation", "conclusion": "Encouragement or predicted outcome" }, "sampleErrors": ["Defining relative clause error", "Strategies listed without explanation", "No motivating conclusion"] },
  { "grade": 9, "unit": 10, "title": "Planet Earth", "topic": "Flora, fauna and environmental threats", "writingTask": "Write a summary about a topic", "taskType": "descriptive", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["habitat", "species", "biodiversity", "threaten", "extinct", "conservation"], "targetGrammar": ["non-defining relative clauses", "passive voice", "rhythm in sentences"], "writingStructure": { "topicSentence": "State the main topic of the summary", "body": "Paraphrase key information from the source", "conclusion": "Main takeaway or implication" }, "sampleErrors": ["Copying source text verbatim instead of paraphrasing", "Non-defining relative clause punctuation missing", "No clear main idea statement"] },
  { "grade": 9, "unit": 11, "title": "Electronic Devices", "topic": "Electronic devices and their uses", "writingTask": "Write a passage about the current and future capabilities of one's favourite electronic device", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["capability", "feature", "upgrade", "artificial intelligence", "smart device", "portable"], "targetGrammar": ["suggest/advise/recommend + V-ing or clause with should", "future simple and modals: might/could", "because/as a result"], "writingStructure": { "topicSentence": "Name the device and its most important current use", "body": "Describe current capabilities and predict future ones", "conclusion": "Impact on life in the future" }, "sampleErrors": ["Recommend + infinitive (incorrect) instead of V-ing", "Current and future capabilities not distinguished", "No prediction for the future"] },
  { "grade": 9, "unit": 12, "title": "Career Choices", "topic": "Future jobs and career paths", "writingTask": "Write an email about your future favourite job", "taskType": "descriptive", "targetWordCount": { "min": 100, "max": 120 }, "keyVocabulary": ["career", "profession", "qualification", "salary", "ambition", "opportunity"], "targetGrammar": ["adverbial clauses of concession, result, and reason", "intonation in statements as questions", "future simple and present perfect"], "writingStructure": { "topicSentence": "Name the career and why you want it", "body": "Describe what the job involves and what qualifications you need", "conclusion": "How you plan to achieve your goal" }, "sampleErrors": ["Adverbial clause connector confused (although vs because)", "No plan or action mentioned", "Email format not used"] },
  { "grade": 10, "unit": 1, "title": "Family Life", "topic": "Family roles and household routines", "writingTask": "Write about family routines", "taskType": "descriptive", "targetWordCount": { "min": 120, "max": 150 }, "keyVocabulary": ["breadwinner", "chore", "routine", "divide", "responsibility", "household"], "targetGrammar": ["present simple vs present continuous", "frequency adverbs", "linking words"], "writingStructure": { "topicSentence": "Describe your family's typical daily routine", "body": "Detail who does what and when in the family", "conclusion": "Comment on fairness or your personal feelings about the routines" }, "sampleErrors": ["Present simple vs continuous confusion for habits", "Routine described without any personal opinion", "No concluding reflection"] },
  { "grade": 10, "unit": 2, "title": "Humans and the Environment", "topic": "Environmental issues and green living", "writingTask": "Write about ways to improve the environment", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 120, "max": 150 }, "keyVocabulary": ["carbon footprint", "renewable", "sustainable", "recycle", "emission", "habitat"], "targetGrammar": ["future with will and be going to", "passive voice", "because/as a result/therefore"], "writingStructure": { "topicSentence": "Introduce the environmental issue", "body": "Give 3 specific actions people can take", "conclusion": "Impact if actions are widely adopted" }, "sampleErrors": ["Will vs be going to confusion", "Passive voice structure incorrect", "Actions listed without explaining their impact"] },
  { "grade": 10, "unit": 3, "title": "Music", "topic": "Music genres and experiences", "writingTask": "Write a blog about experiences at a music event", "taskType": "descriptive", "targetWordCount": { "min": 120, "max": 150 }, "keyVocabulary": ["genre", "performance", "festival", "atmosphere", "audience", "live music"], "targetGrammar": ["compound sentences", "to-infinitives and bare infinitives", "past simple for narrative"], "writingStructure": { "topicSentence": "Introduce the event and your overall impression", "body": "Describe the venue, performances, and atmosphere", "conclusion": "How you felt and whether you would go again" }, "sampleErrors": ["Blog format not used (no casual register)", "Bare infinitive vs to-infinitive error", "No personal opinion or recommendation"] },
  { "grade": 10, "unit": 4, "title": "For a Better Community", "topic": "Volunteering and community development", "writingTask": "Write an application letter for volunteer work", "taskType": "noticeWriting", "targetWordCount": { "min": 120, "max": 150 }, "keyVocabulary": ["volunteer", "application", "experience", "commitment", "skill", "community"], "targetGrammar": ["past simple vs past continuous with when and while", "adjective suffixes: -ed, -ing, -ful, -less", "formal register"], "writingStructure": { "topicSentence": "Opening paragraph: state the position you are applying for", "body": "Describe relevant experience and skills; explain why you want to volunteer", "conclusion": "Express enthusiasm and availability" }, "sampleErrors": ["Informal language used in formal letter", "When/while clause form error", "No specific skills or experiences mentioned"] },
  { "grade": 10, "unit": 5, "title": "Inventions", "topic": "Famous inventions and their benefits", "writingTask": "Write about the benefits of an invention", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 120, "max": 150 }, "keyVocabulary": ["invention", "patent", "revolutionise", "efficiency", "breakthrough", "impact"], "targetGrammar": ["present perfect", "gerunds and to-infinitives", "as a result/therefore/consequently"], "writingStructure": { "topicSentence": "Name the invention and its most important benefit", "body": "Give 3 benefits with specific examples", "conclusion": "Overall impact of the invention on human life" }, "sampleErrors": ["Present perfect form error", "Benefits stated without examples or evidence", "Conclusion simply repeats the introduction"] },
  { "grade": 10, "unit": 6, "title": "Gender Equality", "topic": "Gender equality in work and society", "writingTask": "Write about jobs for men and women", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 120, "max": 150 }, "keyVocabulary": ["gender equality", "discrimination", "stereotype", "opportunity", "bias", "empowerment"], "targetGrammar": ["passive voice with modals", "comparative and superlative adjectives", "although/however/despite"], "writingStructure": { "topicSentence": "State position on gender equality in the workplace", "body": "Compare opportunities for men and women; give evidence of inequality", "conclusion": "What should be done to achieve equality" }, "sampleErrors": ["Passive + modal form error", "Opinion stated without supporting evidence", "No solution or call to action in conclusion"] },
  { "grade": 10, "unit": 7, "title": "Viet Nam and International Organisations", "topic": "Viet Nam's participation in international organisations", "writingTask": "Write about Viet Nam's participation in international organisations", "taskType": "descriptive", "targetWordCount": { "min": 120, "max": 150 }, "keyVocabulary": ["ASEAN", "UNICEF", "membership", "cooperation", "treaty", "international"], "targetGrammar": ["comparative and superlative adjectives", "passive voice", "because/as a result"], "writingStructure": { "topicSentence": "Name the organisation and Viet Nam's role", "body": "Describe what the organisation does and Viet Nam's contributions", "conclusion": "Benefits of membership for Viet Nam" }, "sampleErrors": ["Passive construction incorrect", "Organisation described without Viet Nam's specific role", "Benefits too vague"] },
  { "grade": 10, "unit": 8, "title": "New Ways to Learn", "topic": "Online and blended learning", "writingTask": "Write about the benefits of blended learning", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 120, "max": 150 }, "keyVocabulary": ["blended learning", "flexible", "self-paced", "engagement", "technology", "face-to-face"], "targetGrammar": ["relative clauses: defining and non-defining", "who, that, which, whose", "however/on the other hand"], "writingStructure": { "topicSentence": "Define blended learning and state main claim", "body": "Give 3 benefits with explanation and examples", "conclusion": "Recommendation for wider adoption" }, "sampleErrors": ["Relative pronoun choice error (who vs which)", "Benefits stated without examples", "No recommendation in conclusion"] },
  { "grade": 10, "unit": 9, "title": "Protecting the Environment", "topic": "Environmental protection and wildlife", "writingTask": "Write about a wildlife organisation", "taskType": "descriptive", "targetWordCount": { "min": 120, "max": 150 }, "keyVocabulary": ["conservation", "endangered", "WWF", "habitat", "biodiversity", "awareness"], "targetGrammar": ["reported speech", "passive voice", "because/therefore/as a result"], "writingStructure": { "topicSentence": "Name the organisation and its main mission", "body": "Describe key projects and achievements", "conclusion": "Why the organisation's work matters" }, "sampleErrors": ["Reported speech tense shift incorrect", "Organisation described in vague terms", "No statement of importance at the end"] },
  { "grade": 10, "unit": 10, "title": "Ecotourism", "topic": "Ecotourism and sustainable travel", "writingTask": "Write a website advertisement for an ecotour", "taskType": "noticeWriting", "targetWordCount": { "min": 120, "max": 150 }, "keyVocabulary": ["ecotour", "sustainable", "biodiversity", "community", "responsible travel", "wildlife"], "targetGrammar": ["conditional sentences type 1 and type 2", "intonation", "persuasive language"], "writingStructure": { "topicSentence": "Headline and opening hook", "body": "Describe what the tour offers: destination, activities, impact", "conclusion": "Call to action: how to book" }, "sampleErrors": ["Conditional type 2 form error (if + past simple, would + base)", "Advertisement register too formal", "No call to action"] },
  { "grade": 11, "unit": 1, "title": "A Long and Healthy Life", "topic": "Health, fitness, and longevity", "writingTask": "Write a short message about a health topic", "taskType": "descriptive", "targetWordCount": { "min": 130, "max": 160 }, "keyVocabulary": ["longevity", "fitness", "nutrition", "mental health", "habit", "wellbeing"], "targetGrammar": ["past simple vs present perfect", "strong and weak forms of auxiliary verbs", "because/therefore"], "writingStructure": { "topicSentence": "Introduce the health message and its purpose", "body": "Give 2–3 health tips with reasons", "conclusion": "Motivational closing" }, "sampleErrors": ["Present perfect vs past simple confusion", "Tips given without reasons", "No motivational closing"] },
  { "grade": 11, "unit": 2, "title": "The Generation Gap", "topic": "Generational differences and family conflict", "writingTask": "Write an opinion essay about limiting teenagers' screen time", "taskType": "agreeDisagree", "targetWordCount": { "min": 150, "max": 180 }, "keyVocabulary": ["screen time", "addiction", "generation gap", "conflict", "boundary", "digital native"], "targetGrammar": ["modal verbs: must, have to, should", "contracted forms", "linking words for opinion: I believe, in my opinion"], "writingStructure": { "topicSentence": "State position clearly on screen time limits", "body": "Give 2 arguments for the position with reasons/examples; acknowledge one counter-argument", "conclusion": "Restate position and call to action" }, "sampleErrors": ["Must vs have to confused", "Counter-argument missing", "Position not clearly restated in conclusion"] },
  { "grade": 11, "unit": 3, "title": "Cities of the Future", "topic": "Smart cities and urban living", "writingTask": "Write an article about the advantages and disadvantages of living in a smart city", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 150, "max": 180 }, "keyVocabulary": ["smart city", "infrastructure", "sensor", "efficiency", "privacy", "sustainable"], "targetGrammar": ["stative verbs in continuous form", "linking verbs", "on the other hand/however/despite"], "writingStructure": { "topicSentence": "Introduce smart cities and the debate about them", "body": "Give 2 advantages and 2 disadvantages with evidence", "conclusion": "Balanced overall assessment" }, "sampleErrors": ["Stative verb used in continuous form (e.g. 'is seeming')", "Advantages and disadvantages not balanced", "No overall assessment in conclusion"] },
  { "grade": 11, "unit": 4, "title": "ASEAN and Viet Nam", "topic": "ASEAN membership and cooperation", "writingTask": "Write a proposal for a welcome event", "taskType": "noticeWriting", "targetWordCount": { "min": 150, "max": 180 }, "keyVocabulary": ["proposal", "ASEAN", "cooperation", "event", "programme", "participant"], "targetGrammar": ["gerunds as subjects and objects", "to-infinitives of purpose", "formal register"], "writingStructure": { "topicSentence": "Purpose of the proposal and what the event is", "body": "Describe planned activities, venue, schedule, and expected outcomes", "conclusion": "Request for approval or support" }, "sampleErrors": ["Gerund vs infinitive error", "Proposal too informal", "No clear purpose or request at the end"] },
  { "grade": 11, "unit": 5, "title": "Global Warming", "topic": "Climate change and environmental action", "writingTask": "Write a leaflet to persuade people to reduce black carbon emissions", "taskType": "noticeWriting", "targetWordCount": { "min": 150, "max": 180 }, "keyVocabulary": ["black carbon", "emission", "climate change", "fossil fuel", "renewable energy", "reduce"], "targetGrammar": ["present participle clauses", "past participle clauses", "imperative for persuasion"], "writingStructure": { "topicSentence": "Headline and alarming opening fact", "body": "Explain the problem; give 3 actions readers can take", "conclusion": "Call to action with urgency" }, "sampleErrors": ["Participle clause construction incorrect", "Leaflet format not used (no headlines, sub-headings)", "No sense of urgency in conclusion"] },
  { "grade": 11, "unit": 6, "title": "Preserving Our Heritage", "topic": "Cultural heritage preservation", "writingTask": "Write a leaflet to inform people about ways to preserve Trang An Scenic Landscape Complex", "taskType": "noticeWriting", "targetWordCount": { "min": 150, "max": 180 }, "keyVocabulary": ["heritage", "preservation", "UNESCO", "landscape", "restore", "awareness"], "targetGrammar": ["to-infinitive clauses", "intonation in statements, commands, lists", "passive voice"], "writingStructure": { "topicSentence": "Introduce Trang An and why it needs protection", "body": "Give 3 ways visitors or locals can help preserve it", "conclusion": "Appeal to the reader's sense of responsibility" }, "sampleErrors": ["To-infinitive clause position incorrect", "Leaflet too academic — lacks accessible language", "No call to action"] },
  { "grade": 11, "unit": 7, "title": "Education Options for School-Leavers", "topic": "Study and career options after secondary school", "writingTask": "Write a request letter to ask for information about vocational school courses", "taskType": "noticeWriting", "targetWordCount": { "min": 150, "max": 180 }, "keyVocabulary": ["vocational", "qualification", "apprenticeship", "curriculum", "enrolment", "prospectus"], "targetGrammar": ["perfect gerunds and perfect participles", "intonation in Wh- and Yes/No questions", "formal letter register"], "writingStructure": { "topicSentence": "State why you are writing and which school", "body": "Ask 3–4 specific questions about courses, duration, fees", "conclusion": "Thank the reader and give contact details" }, "sampleErrors": ["Perfect gerund form incorrect", "Questions too vague or informal", "No contact information or polite closing"] },
  { "grade": 11, "unit": 8, "title": "Becoming Independent", "topic": "Teen independence and life skills", "writingTask": "Write an article about the pros and cons of self-study", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 150, "max": 180 }, "keyVocabulary": ["self-study", "discipline", "motivation", "autonomous", "distraction", "skill"], "targetGrammar": ["cleft sentences: It is/was ... that clause", "intonation in invitations, suggestions, polite requests", "however/on the other hand/despite"], "writingStructure": { "topicSentence": "Introduce self-study and state the main tension", "body": "Give 2 pros and 2 cons with evidence", "conclusion": "Balanced recommendation" }, "sampleErrors": ["Cleft sentence construction incorrect", "Only pros OR cons given — no balance", "Recommendation missing from conclusion"] },
  { "grade": 11, "unit": 9, "title": "Social Issues", "topic": "Peer pressure and cyberbullying", "writingTask": "Write a proposal for a school campaign against cyberbullying", "taskType": "noticeWriting", "targetWordCount": { "min": 150, "max": 180 }, "keyVocabulary": ["cyberbullying", "campaign", "awareness", "peer pressure", "digital literacy", "bystander"], "targetGrammar": ["linking words and phrases", "intonation in choice questions", "formal proposal register"], "writingStructure": { "topicSentence": "State the problem and purpose of the campaign", "body": "Describe planned activities, target audience, timeline", "conclusion": "Expected outcomes and request for support" }, "sampleErrors": ["Proposal structure not followed", "Activities described without expected outcomes", "Register too informal for a school proposal"] },
  { "grade": 11, "unit": 10, "title": "The Ecosystem", "topic": "Local ecosystems and biodiversity", "writingTask": "Write an opinion essay about spending money on restoring local ecosystems", "taskType": "agreeDisagree", "targetWordCount": { "min": 150, "max": 180 }, "keyVocabulary": ["ecosystem", "restoration", "biodiversity", "funding", "extinct", "habitat"], "targetGrammar": ["compound nouns", "intonation in question tags", "however/although/despite/in contrast"], "writingStructure": { "topicSentence": "State position clearly on ecosystem funding", "body": "Give 2 strong arguments; acknowledge counter-argument and refute it", "conclusion": "Restate position with a call to action" }, "sampleErrors": ["Counter-argument not acknowledged", "Compound noun form incorrect", "Position not restated clearly in conclusion"] },
  { "grade": 12, "unit": 1, "title": "Life Stories We Admire", "topic": "Inspiring life stories and achievements", "writingTask": "Synthesise and summarise information to write a biography", "taskType": "descriptive", "targetWordCount": { "min": 160, "max": 200 }, "keyVocabulary": ["achievement", "milestone", "biography", "legacy", "inspire", "overcome"], "targetGrammar": ["past simple vs past continuous", "diphthongs", "linking words for narrative"], "writingStructure": { "topicSentence": "Introduce the person and their significance", "body": "Chronological account of key life events and achievements", "conclusion": "Legacy and why they are admirable" }, "sampleErrors": ["Chronology unclear or jumbled", "Synthesising — copying source text instead of paraphrasing", "No concluding statement of legacy or impact"] },
  { "grade": 12, "unit": 2, "title": "A Multicultural World", "topic": "Cultural diversity and globalisation", "writingTask": "Write an opinion essay about the impact of world festivals on young Vietnamese people", "taskType": "agreeDisagree", "targetWordCount": { "min": 160, "max": 200 }, "keyVocabulary": ["globalisation", "cultural exchange", "identity", "assimilation", "diversity", "influence"], "targetGrammar": ["articles: review and extension", "diphthongs /ɔɪ/, /aɪ/, /aʊ/", "I believe/argue/contend that"], "writingStructure": { "topicSentence": "State position on impact of world festivals", "body": "2 arguments supporting the position; 1 counter-argument with rebuttal", "conclusion": "Restate position and broader implication" }, "sampleErrors": ["Article misuse (missing 'the' for specific references)", "Counter-argument without rebuttal", "Conclusion too short or repetitive"] },
  { "grade": 12, "unit": 3, "title": "Green Living", "topic": "Environmental sustainability and green solutions", "writingTask": "Write a problem-solving report on green solutions", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 160, "max": 200 }, "keyVocabulary": ["sustainability", "compost", "carbon neutral", "renewable", "recycle", "eco-friendly"], "targetGrammar": ["verbs with prepositions", "relative clauses referring to whole sentence", "formal report register"], "writingStructure": { "topicSentence": "Identify the environmental problem", "body": "Analyse causes and propose 3 green solutions", "conclusion": "Recommend the most effective solution with justification" }, "sampleErrors": ["Relative clause punctuation incorrect", "Solutions proposed without analysis of why they work", "No single clear recommendation at the end"] },
  { "grade": 12, "unit": 4, "title": "Urbanisation", "topic": "Trends and effects of urbanisation", "writingTask": "Describe a line graph about trends in urbanisation", "taskType": "descriptive", "targetWordCount": { "min": 160, "max": 200 }, "keyVocabulary": ["urbanisation", "trend", "rate", "rural-urban migration", "infrastructure", "data"], "targetGrammar": ["present perfect: review and extension", "double comparatives", "language for describing trends: rise, fall, peak, stabilise"], "writingStructure": { "topicSentence": "Introduce the graph and its overall trend", "body": "Describe key data points, peaks, troughs, and comparisons", "conclusion": "Overall trend and implication" }, "sampleErrors": ["Trend vocabulary used incorrectly (e.g. rise used as noun and verb confused)", "Data described without comparison", "No overall conclusion about what the trend means"] },
  { "grade": 12, "unit": 5, "title": "The World of Work", "topic": "Jobs, careers, and job applications", "writingTask": "Write a job application letter", "taskType": "noticeWriting", "targetWordCount": { "min": 160, "max": 200 }, "keyVocabulary": ["application", "vacancy", "qualification", "reference", "salary", "responsibility"], "targetGrammar": ["simple, compound, and complex sentences: review", "stressing auxiliary and modal verbs", "formal letter conventions"], "writingStructure": { "topicSentence": "State the position applied for and where you saw it", "body": "Describe qualifications, relevant experience, and key strengths", "conclusion": "Express enthusiasm, availability for interview, and sign off formally" }, "sampleErrors": ["Sentence structure too simple for B1+ level", "Experience described too vaguely", "Informal closing (e.g. 'See you soon' instead of 'Yours sincerely')"] },
  { "grade": 12, "unit": 6, "title": "Artificial Intelligence", "topic": "AI applications and implications", "writingTask": "Write about AI applications in education", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 160, "max": 200 }, "keyVocabulary": ["artificial intelligence", "machine learning", "algorithm", "personalisation", "automation", "ethics"], "targetGrammar": ["active and passive causatives", "homophones", "however/on the other hand/in contrast"], "writingStructure": { "topicSentence": "Introduce AI in education and the key debate", "body": "Give 2 benefits and 2 concerns with evidence", "conclusion": "Balanced recommendation for responsible AI use in education" }, "sampleErrors": ["Causative structure incorrect (have/get + object + past participle)", "Benefits and concerns not balanced", "No nuanced conclusion — too one-sided"] },
  { "grade": 12, "unit": 7, "title": "The World of Mass Media", "topic": "Digital vs traditional media", "writingTask": "Write an article comparing digital and traditional media", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 160, "max": 200 }, "keyVocabulary": ["digital media", "broadcast", "credibility", "audience", "print media", "social media"], "targetGrammar": ["adverbial clauses of manner and result", "linking /r/ between vowels", "while/whereas/in contrast"], "writingStructure": { "topicSentence": "Introduce the shift from traditional to digital media", "body": "Compare 3 aspects: speed, credibility, and reach", "conclusion": "Which form of media is more valuable and why" }, "sampleErrors": ["Adverbial clause of manner construction incorrect", "Comparison made without specific evidence", "No clear verdict in conclusion"] },
  { "grade": 12, "unit": 8, "title": "Wildlife Conservation", "topic": "Wildlife conservation and endangered species", "writingTask": "Write about wildlife conservation efforts", "taskType": "advantagesDisadvantages", "targetWordCount": { "min": 160, "max": 200 }, "keyVocabulary": ["conservation", "endangered", "poaching", "sanctuary", "wildlife corridor", "biodiversity"], "targetGrammar": ["adverbial clauses of condition and comparison", "assimilation", "however/despite/in spite of"], "writingStructure": { "topicSentence": "State the threat to wildlife and the need for conservation", "body": "Describe 3 conservation strategies and their effectiveness", "conclusion": "Most important strategy and call to action" }, "sampleErrors": ["Adverbial clause of condition form error", "Strategies described without assessing effectiveness", "No call to action"] },
  { "grade": 12, "unit": 9, "title": "Career Paths", "topic": "Choosing a career path", "writingTask": "Write about things to consider when choosing a career path", "taskType": "descriptive", "targetWordCount": { "min": 160, "max": 200 }, "keyVocabulary": ["career path", "aptitude", "interest", "job market", "salary", "work-life balance"], "targetGrammar": ["three-word phrasal verbs", "sentence stress and rhythm", "because/considering/given that"], "writingStructure": { "topicSentence": "Introduce the importance of careful career planning", "body": "Discuss 3 key factors to consider", "conclusion": "Advice for making a wise career choice" }, "sampleErrors": ["Three-word phrasal verb used incorrectly", "Factors listed without explanation of why they matter", "Conclusion is generic — no specific advice"] },
  { "grade": 12, "unit": 10, "title": "Lifelong Learning", "topic": "The value of continued learning", "writingTask": "Write about lifelong learning", "taskType": "agreeDisagree", "targetWordCount": { "min": 160, "max": 200 }, "keyVocabulary": ["lifelong learning", "continuous development", "adaptability", "upskilling", "knowledge economy", "curiosity"], "targetGrammar": ["reported speech: reporting orders, requests, offers, advice", "intonation in questions (revision)", "I believe/It can be argued that/In conclusion"], "writingStructure": { "topicSentence": "State position on the value of lifelong learning", "body": "Give 2 arguments; address one objection and rebut it", "conclusion": "Restate position with a forward-looking statement" }, "sampleErrors": ["Reported speech tense backshift incorrect", "Objection raised but not rebutted", "Conclusion too brief or just repeats introduction"] }
]

// ── Helper functions ──────────────────────────────────────────────

function getUnitData(grade, unit) {
  return CURRICULUM.find(c => c.grade === grade && c.unit === unit) || null
}

function getGradeData(grade) {
  return CURRICULUM.filter(c => c.grade === grade)
}

function getCurriculumContext(grade, unitTopic, taskType) {
  const gradeUnits = getGradeData(grade)

  const match = gradeUnits.find(u =>
    u.topic.toLowerCase().includes(unitTopic?.toLowerCase()?.split(' ')[0] || '') ||
    u.title.toLowerCase().includes(unitTopic?.toLowerCase()?.split(' ')[0] || '')
  ) || gradeUnits.find(u => u.taskType === taskType)

  if (!match) return null

  return {
    title: match.title,
    topic: match.topic,
    taskType: match.taskType,
    targetWordCount: match.targetWordCount,
    keyVocabulary: match.keyVocabulary,
    targetGrammar: match.targetGrammar,
    writingStructure: match.writingStructure,
    sampleErrors: match.sampleErrors
  }
}

module.exports = { CURRICULUM, getUnitData, getGradeData, getCurriculumContext }
